apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  labels:
    app: pulselink
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulselink
      component: worker
  template:
    metadata:
      labels:
        app: pulselink
        component: worker
    spec:
      containers:
        - name: worker-service
          image: <ECR_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/pulselink-worker:latest
          envFrom:
            - configMapRef:
                name: pulselink-config
            - secretRef:
                name: pulselink-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
